nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:\d+)?$']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':
            origin_regex: true
