nelmio_cors:
    defaults:
        allow_origin: ['https://localhost:5173', 'http://localhost:5173', 'https://127.0.0.1:5173', 'http://127.0.0.1:5173', 'https://groupe-5.lycee-stvincent.net']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['Link']
        max_age: 7200
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['https://localhost:5173', 'http://localhost:5173', 'https://127.0.0.1:5173', 'http://127.0.0.1:5173', 'https://groupe-5.lycee-stvincent.net']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['*']
            expose_headers: ['Link']
            max_age: 7200
        '^/uploads/':
            allow_origin: ['https://localhost:5173', 'http://localhost:5173', 'https://127.0.0.1:5173', 'http://127.0.0.1:5173', 'https://groupe-5.lycee-stvincent.net']
            allow_methods: ['GET']
            allow_headers: ['*']
            expose_headers: ['Content-Type']
            max_age: 3600
