security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern:   ^/api
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/offers/search, roles: PUBLIC_ACCESS }
        - { path: ^/api/offers, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/user/new, roles: PUBLIC_ACCESS } 
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
