vich_uploader:
    db_driver: orm

    mappings:
       photos_offer:
           uri_prefix: /uploads/offers-photos
           upload_destination: '%kernel.project_dir%/public/uploads/offers-photos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
